### ISSUE TITLE
Uncaught Error: Cannot find module 'space-pen'

### ISSUE THREAD

**Issue by rajendrant** [sphaerophoria/atom-rtags-plus#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Ubuntu 14.04
**Thrown From**: [atom-rtags-plus](https://github.com/sphaerophoria/atom-rtags-plus) package 1.4.2

### Stack Trace

Uncaught Error: Cannot find module 'space-pen'

```
At /usr/share/atom/resources/app/static/<embedded>:1

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-rtags-plus/lib/view/rtags-search-view.coffee:1:13)
    at /packages/atom-rtags-plus/lib/view/rtags-search-view.coffee:1:1)
    at /packages/atom-rtags-plus/lib/view/rtags-search-view.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at lazy (/packages/atom-rtags-plus/node_modules/lazy-req/index.js:2:51)
    at Object.get (/packages/atom-rtags-plus/node_modules/lazy-req/index.js:42:11)
    at Object.getSearchView (/packages/atom-rtags-plus/lib/atom-rtags.coffee:227:41)
    at Object.refactorAtPoint (/packages/atom-rtags-plus/lib/atom-rtags.coffee:217:6)
    at /packages/atom-rtags-plus/lib/atom-rtags.coffee:100:104)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:45.1.0 core:cancel (input.hidden-input)
     -0:44.3.0 command-palette:toggle (input.hidden-input)
     -0:35.4.0 editor:consolidate-selections (input.hidden-input)
     -0:35.4.0 core:cancel (input.hidden-input)
     -0:27.4.0 core:move-up (input.hidden-input)
     -0:27 core:move-down (input.hidden-input)
  5x -0:24.3.0 editor:move-to-end-of-word (input.hidden-input)
     -0:22.7.0 core:move-right (input.hidden-input)
  3x -0:22.2.0 core:move-up (input.hidden-input)
  3x -0:21.4.0 core:move-left (input.hidden-input)
     -0:16.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:14.8.0 editor:consolidate-selections (input.hidden-input)
     -0:14.8.0 core:cancel (input.hidden-input)
     -0:14.3.0 command-palette:toggle (input.hidden-input)
     -0:09.1.0 core:confirm (input.hidden-input)
     -0:09.1.0 atom-rtags-plus:refactor-at-point (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-rtags 0.2.2 
atom-rtags-plus 1.4.2 
autocomplete-clang 0.8.8 
build 0.68.0 
clipboard-plus 0.5.1 
highlight-selected 0.13.1 
hyperclick 0.1.3 
language-diff 0.7.0 
linter 2.2.0 
linter-clang 4.1.2 
minimap 4.29.6 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
multirow-tabs 0.3.3 
my-misc 0.0.0 
sane-indentation 0.1.3 
smart-tab-name 1.0.5 
tab-switcher 1.5.6 
```

**Comment by rajendrant** [comment]
This error went away when I did one or all of the following.

apm uninstall linter && apm install linter
Reinstall atom-rtags-plus

https://github.com/steelbrain/linter/issues/510
