### ISSUE TITLE
Uncaught TypeError: editor.getRootScopeDescriptor is not a function

### ISSUE THREAD

**Issue by phord** [sphaerophoria/atom-rtags-plus#8]
[Enter steps to reproduce:]

1. Upgraded atom today to 1.17.2
2. Got this error at startup

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.10
**Thrown From**: [atom-rtags-plus](https://github.com/sphaerophoria/atom-rtags-plus) package 1.4.2

### Stack Trace

Uncaught TypeError: editor.getRootScopeDescriptor is not a function

```
At /home/phord/.atom/packages/atom-rtags-plus/lib/util.js:41

TypeError: editor.getRootScopeDescriptor is not a function
    at Proxy.module.exports.matched_scope (/packages/atom-rtags-plus/lib/util.js:41:38)
    at OpenFileTracker.updateRecentlyViewedItems (/packages/atom-rtags-plus/lib/open-file-tracker.js:16:47)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:129:1)
    at Workspace.didActivatePaneContainer (/usr/share/atom/resources/app/src/workspace.js:474:1)
    at WorkspaceCenter.paneContainer.onDidActivatePane (/usr/share/atom/resources/app/src/workspace-center.js:11:1)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:129:1)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/src/pane-container.js:260:1)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app/src/pane.js:875:1)
    at Pane.module.exports.Pane.focus (/usr/share/atom/resources/app/src/pane.js:269:1)
    at atom-pane.<anonymous> (/usr/share/atom/resources/app/src/pane-element.js:51:25)
```

### Commands

```
     -0:29.4.0 nuclide-file-tree:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:29.4.0 nuclide-file-tree:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-rtags-plus 1.4.2 
busy-signal 1.4.1 
clipboard-plus 0.5.1 
file-type-icons 1.3.4 
git-status 0.3.4 
git-time-machine 1.5.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
language-babel 2.65.1 
language-docker 1.1.8 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.3 
language-openscad 0.4.3 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
line-diff-details 1.8.0 
linter 2.1.4 
linter-ui-default 1.6.0 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
nuclide 0.230.0 
nuclide-format-js 0.0.36 
screen-recorder 1.2.3 
set-syntax 0.3.2 
sort-lines 0.14.0 
ssh-config 0.10.1 
tool-bar 1.1.0 
```

**Comment by phord** [comment]
For different reasons, I built atom from source today to update to the current master (1.19.0).  This error does not appear in the tip.  Maybe it was a problem only with 1.17?
